fix(launchpad): retry create recipes if launchpad error
canonical/craft-application pull request #278
Opened 2024-03-19 23:02 UTC by syu-w

2024-03-20 17:03 UTC, mr-cal approved these changes

2024-03-21 14:38 UTC, sergiusens commented on craft_application/launchpad/models/recipe.py
> +            except lazr.restfulclient.errors.BadRequest:
emit a debug message here

2024-03-21 14:40 UTC, sergiusens commented on craft_application/launchpad/models/recipe.py
> +                charm_entry = lp.lp.charm_recipes.new(
emit a debug message here, something like f"Trying to Create project ({attempt}/{_ATTEMPT_COUNT}"

2024-03-21 14:40 UTC, sergiusens commented on craft_application/launchpad/models/recipe.py
> +                snap_entry = lp.lp.snaps.new(
emit a debug message here, something like f"Trying to Create project ({attempt}/{_ATTEMPT_COUNT}"

2024-03-21 15:53 UTC, lengau requested changes
Thanks!

Could you add some unit tests for this, mocking out the snaps `new` method and raising exceptions an appropriate number of times to check retry-success and retry-failure cases?

2024-03-21 19:13 UTC, lengau approved these changes
Excellent, thanks!

2024-03-21 19:13 UTC, merged