chore: add a CODEOWNERS file
canonical/craft-application pull request #589
Opened 2024-12-12 04:37 UTC by lengau

- [ ] Have you followed the guidelines for contributing?
- [ ] Have you signed the [CLA](http://www.ubuntu.com/legal/contributors/)?
- [ ] Have you successfully run `tox`?

-----

2024-12-12 12:35 UTC, tigarmo requested changes

2024-12-12 12:35 UTC, tigarmo commented on .github/CODEOWNERS
> +/craft_application/serices/fetch.py  @tigarmo @lengau
```suggestion
/craft_application/services/fetch.py  @tigarmo @lengau
```

2024-12-12 23:42 UTC, lengau commented on .github/CODEOWNERS
> +/craft_application/serices/fetch.py  @tigarmo @lengau
Good catch, thanks!

2024-12-13 11:31 UTC, tigarmo approved these changes

2025-06-06 19:56 UTC, closed without merging